#!/usr/bin/env python3
"""
Flow Kit — AI Tool Setup
Generates AI tool configs from skills/fk-*.md (single source of truth).

Usage:
    python setup.py                  # Interactive: pick your AI tool(s)
    python setup.py --tool claude    # Generate for Claude Code
    python setup.py --tool codex     # Generate for Codex
    python setup.py --tool all       # Generate for all tools
    python setup.py sync             # Re-sync all previously selected tools
    python setup.py clean            # Remove all generated tool configs

The Gemini CLI target was removed in v1.3.1. The Gemini CLI is retired, and
its replacement `agy` (Antigravity) reads none of what that target produced —
verified against agy 1.2.7: a project's `.gemini/commands/*.toml` is not
expanded, `.claude/commands/*.md` is not either, and `GEMINI.md`, `AGENTS.md`
and `CLAUDE.md` are all absent from a print-mode run's context even inside a
trusted folder. agy's own commands come from its plugin system
(`agy plugin import`), which imports extensions rather than command files.

`agy` is still a first-class part of Flow Kit — as one of the three AI CLIs
that can run video review. That is configured in `agent/providers.json` via
`/fk-change-provider` or the dashboard, not here: this script generates
per-project command files for the CLI you *drive* Flow Kit from.
"""

import argparse
import json
import shutil
import sys
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path(__file__).parent
SKILLS_DIR = ROOT / "skills"
CLAUDE_COMMANDS_DIR = ROOT / ".claude" / "commands"
AGENTS_MD = ROOT / "AGENTS.md"
ANTIGRAVITY_SKILLS_DIR = ROOT / ".agents" / "skills"
STATE_FILE = ROOT / ".fk-setup.json"

# Nothing generates these any more; `clean` still removes them so an install
# from before v1.3.1 does not keep stale files for a CLI that no longer exists.
LEGACY_GEMINI_COMMANDS_DIR = ROOT / ".gemini" / "commands" / "fk"
LEGACY_GEMINI_MD = ROOT / "GEMINI.md"


def _split_frontmatter(text):
    """Split a leading YAML frontmatter block off; return (frontmatter, body)."""
    if text.startswith("---"):
        parts = text.split("---", 2)
        if len(parts) >= 3:
            return parts[1], parts[2].lstrip()
    return "", text


def discover_skills():
    """Scan skills/fk-*.md and skills/fk-*/SKILL.md for name + description.

    A flat skill's description is its first line. A folder skill (SKILL.md
    plus supporting files such as references/) uses its frontmatter
    `description`, falling back to its first line.
    """
    if not SKILLS_DIR.exists():
        print(f"ERROR: skills/ directory not found at {SKILLS_DIR}")
        return []

    sources = [(p.stem, p, None) for p in SKILLS_DIR.glob("fk-*.md")]
    sources += [(d.name, d / "SKILL.md", d) for d in SKILLS_DIR.glob("fk-*")
                if d.is_dir() and (d / "SKILL.md").is_file()]

    skills = []
    for stem, path, folder in sorted(sources, key=lambda s: s[0]):
        name = stem[len("fk-"):]  # strip "fk-" prefix
        description = ""
        try:
            frontmatter, body = _split_frontmatter(
                path.read_text(encoding="utf-8", errors="replace"))
            for line in frontmatter.splitlines():
                if line.startswith("description:"):
                    description = line[len("description:"):].strip().strip("'\"")
            if not description:
                # Strip leading markdown heading markers
                description = body.splitlines()[0].strip().lstrip("#").strip()
        except (IndexError, OSError):
            description = f"{name} skill"
        skills.append({
            "name": name,
            "description": description,
            "path": str(path),
            "dir": str(folder) if folder else None,
        })

    return skills


def _skill_rel_path(skill):
    """Repo-relative path of a skill's main file, with forward slashes."""
    return Path(skill["path"]).relative_to(ROOT).as_posix()


def generate_claude(skills):
    """Create .claude/commands/fk-<name>.md stubs."""
    CLAUDE_COMMANDS_DIR.mkdir(parents=True, exist_ok=True)
    count = 0
    for skill in skills:
        name = skill["name"]
        desc = skill["description"]
        dest = CLAUDE_COMMANDS_DIR / f"fk-{name}.md"
        content = (
            f"{desc}\n"
            f"<!-- AUTO-GENERATED by setup.py — do not edit. Source: skills/ -->\n"
            f"Read and follow the instructions in {_skill_rel_path(skill)}\n\n"
            f"Arguments: $ARGUMENTS\n"
        )
        dest.write_text(content, encoding="utf-8")
        count += 1
    print(f"Generated {count} Claude commands in .claude/commands/")
    return count


def generate_antigravity(skills):
    """Create .agents/skills/fk-<name>/SKILL.md for Antigravity IDE."""
    ANTIGRAVITY_SKILLS_DIR.mkdir(parents=True, exist_ok=True)
    count = 0
    for skill in skills:
        name = skill["name"]
        skill_id = f"fk-{name}"
        desc = skill["description"]
        src = Path(skill["path"])
        # Strip existing frontmatter if any
        _, body = _split_frontmatter(src.read_text(encoding="utf-8"))

        dest_dir = ANTIGRAVITY_SKILLS_DIR / skill_id
        if dest_dir.exists():
            shutil.rmtree(dest_dir)  # drop supporting files removed at the source
        if skill.get("dir"):
            # Folder skill: carry references/ etc. so relative links resolve.
            shutil.copytree(skill["dir"], dest_dir, ignore=shutil.ignore_patterns("SKILL.md"))
        dest_dir.mkdir(parents=True, exist_ok=True)
        dest = dest_dir / "SKILL.md"

        escaped_desc = desc.replace("'", "''").replace("\n", " ").strip()
        skill_md = (
            f"---\n"
            f"name: {skill_id}\n"
            f"description: '{escaped_desc}'\n"
            f"---\n\n"
            f"{body}\n"
        )
        dest.write_text(skill_md, encoding="utf-8")
        count += 1
    print(f"Generated {count} Antigravity skills in .agents/skills/")
    return count



## ── Inline content for AGENTS.md ──
# Inlined so a non-Claude tool sees the rules directly instead of following a
# "read CLAUDE.md" pointer.
#
# This block is the ONLY source for the generated file. AGENTS.md says
# "do not edit" and was edited anyway: rules 14-16 and pipeline steps 0 and 7.5
# lived only in the generated artifact, so `setup.py sync` would have deleted
# them. They are here now. Anything added to AGENTS.md by hand is lost on the
# next sync — put it here instead.

_CRITICAL_RULES = """\
## Critical Rules (MUST follow)

1. **Media ID is always UUID** — format `xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx`. Never use `CAMS...` / base64 strings.
2. **Scene prompts = ACTION only** — never describe character appearance. Reference images handle visual consistency via `imageInputs`.
3. **All reference images must exist before scene images** — verify every entity has `media_id` before generating scene images.
4. **No throwaway scripts in repo & Scratch Directory Only** — NEVER write Python, shell, or any script file in `scripts/`, `tools/`, or project root to loop over API requests or run temporary test/debug code. Use `POST /api/requests/batch` to submit all requests at once, then poll `GET /api/requests/batch-status`. Any temporary test, debug, or one-off scripts MUST strictly be placed in the conversation scratch directory (`<appDataDir>/brain/<conversation-id>/scratch/`).
5. **Locations use landscape, characters use portrait** — reference image orientation depends on entity type.
6. **UUID extraction** — if a response gives `CAMS...` instead of UUID, extract UUID from the `fifeUrl` in the response URL: `/image/{UUID}?...`.
7. **Cascade on regen** — regenerating an image auto-clears downstream video + upscale.
8. **REGENERATE vs GENERATE** — `GENERATE_*` skips if already COMPLETED. `REGENERATE_*` always runs (clears + regenerates).
9. **Image Material required** — every project needs a `material` field (e.g. `realistic`, `3d_pixar`, `anime`). List available: `GET /api/materials`.
10. **Server handles throttling — EVERY Flow request spaced 45–60s** — every call the server sends to Flow (image/video/upscale submit, image upload, project creation, status polls, metadata reads) waits a random 45–60s after the previous one (`FLOW_GENERATION_MIN_INTERVAL_S=45` / `FLOW_GENERATION_MAX_INTERVAL_S=60` in `agent/config.py`; `VIDEO_POLL_TIMEOUT=900` to fit the slower polls). User-set 2026-10-04: bursts trip `PUBLIC_ERROR_UNUSUAL_ACTIVITY`. Submit ALL requests via `/batch` and let the server pace them; do NOT loop faster. If a script paces its own submits, use `random.uniform(45, 60)` between requests and stop on `UNUSUAL_ACTIVITY` / `QUOTA`.
11. **Video prompts use sub-clip timing** — structure 8s video as time segments: `0-3s: [action]. 3-6s: [action]. 6-8s: [action].`
12. **Character dialogue in sub-clips** — embed speech in quotes: `Luna says "Goodnight."` Max 10-15 words per character per 2-3s segment.
13. **Scenes are mutable** — use `PATCH /api/scenes/{sid}` to update `prompt`, `video_prompt`, `narrator_text`, `character_names` after creation. Don't delete and recreate — patch instead.
14. **Fact-check before scripting** — ALWAYS research events via web search before writing project stories, scene prompts, or narrator text. Facts (events, dates, names, operations, outcomes) MUST match real sources. Editorial opinion and analysis are allowed but must be framed as such. Never invent events, operation names, or statistics. **Exception (user 2026-10-05): time-travel / POV survival vlogs (`/fk-time-travel-vlog`, `/fk-vlog-guide`) are fiction — invention is allowed and research is optional; see the skill's "Hư cấu được phép" section.**
15. **Real-people bypass** — when characters are based on real famous people (politicians, celebrities, military leaders), NEVER use their real name as entity `name` or anywhere in `description`, `image_prompt`, `prompt`, or `video_prompt`. AI image generators reject known public figures. Instead: (a) use a **role-based alias** as entity name (e.g. "Tổng Tư Lệnh" not "Trump", "Thủ Tướng Sắt" not "Netanyahu"), (b) describe **physical appearance only** — distinctive hair, face shape, build, clothing style — without naming who it is, (c) `narrator_text` may use real titles/roles for storytelling but real names never flow into image/video generation. Keep a `real_reference` mapping in the project plan file (`.omc/research/`) for internal tracking.
16. **Review before upscale** — ALWAYS run `/fk-review-video` (light mode) after video generation, before upscaling. Scenes scoring < 7.5 get `video_prompt` updated from review errors, then regen video. Max 2 review-regen cycles.
17. **Auto-retry failed videos (up to 5x)** — When generating videos, any failure or timeout MUST be automatically retried up to 5 times. If failed due to content filters (e.g. `as29s failed: [5]`), auto-sanitize prompt keywords and call `REGENERATE_IMAGE` to get a fresh start frame before regenerating the video.
18. **Rolling download & Review Before Upscale/Clean (Chưa xóa logo khi mới sinh 720p)** — Khi video 720p sinh xong, lập tức tải về `${OUTDIR}/scenes/scene_{idx}_{sid}.mp4`. **TUYỆT ĐỐI CHƯA CẦN XÓA LOGO Ở BƯỚC NÀY** để tránh lãng phí tài nguyên CPU/GPU và thời gian nếu video cần sửa prompt hoặc regen. Trích xuất frame trực tiếp từ video 720p để chạy AI Review Scorecard và đưa lên Review Board cho User duyệt trước. **CHỈ SAU KHI USER DUYỆT CẢNH**: Gửi lệnh Upscale 1080p (`veo_3_1_upsampler_1080p` qua RPC `p0UkFb`), tải video 1080p về thư mục riêng `${OUTDIR}/1080/scene_{idx}_{sid}_1080p.mp4`, rồi mới chạy `remove_watermark_video` trực tiếp trên bản 1080p (`${OUTDIR}/1080/scene_{idx}_{sid}_1080p_clean.mp4`) để đưa vào Concat cuối cùng.
19. **Mandatory review & Review Board** — Pipeline skills (`/fk-pipeline`, `/fk-gen-videos`) MUST automatically execute `/fk-review-video` immediately after video generation, display the per-scene scorecard table showing which nodes passed and which need regeneration, and ensure the Review Board web app (`python tools/review_server.py 8200`) is running.
20. **Language matching for SEO & Thumbnails** — YouTube metadata (`/fk-youtube-seo`) and thumbnails (`/fk-thumbnail`) MUST match the dialogue/script language (e.g. 100% Japanese for Japanese POV vlogs, Vietnamese for Vietnamese, English for English). Never generate English/Vietnamese SEO for Japanese dialogue vlogs.
21. **Flush stale queue on new project** — whenever starting or creating a new project (e.g. `/fk-create-project`, `/fk-time-travel-vlog`), ALWAYS execute `python -c "import sqlite3; conn = sqlite3.connect('flow_agent.db'); conn.execute('UPDATE request SET status=\\'FAILED\\' WHERE status=\\'PENDING\\''); conn.commit()"` first to flush all stale PENDING requests and prevent worker auto-retry loops causing `PUBLIC_ERROR_UNUSUAL_ACTIVITY`.
22. **Mandatory Scene Image Review before Video Generation** — After generating scene images (Step 6), ALWAYS download images locally to `${OUTDIR}/images/scene_{idx}.jpg`, launch the Image Review Board (`review_images.html`), and pause for user review. Never jump directly into video generation without user approval of the scene start frames. Any unsatisfactory images MUST be resubmitted with `REGENERATE_IMAGE`.
23. **Start Frame is Input Reference Only** — The generated scene image (`start_image_media_id` / start frame) serves strictly as the motion starting anchor. Character identity consistency still requires character reference images (`character_names` + `reference_media_ids` / `imageInputs`) to preserve the locked visual identity across the video.
24. **Laomedeia Voice Profile** — For female travel vloggers / narrators, configure `voice_description` using the **Laomedeia** profile (Google Gemini-TTS: upbeat, mid-high pitched, energetic expressive conversational female voice, fast confident vlog delivery with dry humor, rises into real cracking screams when in danger, drops to a fast whisper when hiding). Structure video prompt dialogue accordingly (`Mia says "..."`) so Veo 3 / Pinhole synthesizes matching native vocal audio. In Omni Flash / Pinhole Reference-to-Video (`MZZa6b`), Slot 7 is natively pinned to `[["laomedeia"]]` by default.
25. **Strict Step-by-Step Review Gates (Images then Videos)** — Pipeline execution MUST proceed strictly step-by-step with explicit human review gates:
    - **Step 6.5 (Image Review Gate)**: As soon as scene images are generated, STOP immediately. Clean image watermarks, download all images to `${OUTDIR}/images/scene_{idx}.jpg`, present the image gallery/review board to the user, and PAUSE. Do NOT generate videos until the user explicitly reviews and approves the start frames.
27. **Omni Flash Ingredients Only (Reference-to-Video / `abra_r2v`)** — Khi tạo video cho các dự án vlog/nhân vật, **TUYỆT ĐỐI KHÔNG tạo ảnh Start Frame (`GENERATE_IMAGE`) rồi chạy Image-to-Video (`i2v`)**. Phương pháp start-frame làm chuyển động bị cứng, dễ méo người và biến dạng khuôn mặt khi chuyển động. **BẮT BUỘC chỉ sử dụng Omni Flash Ingredients (`GENERATE_VIDEO_REFS` / `omni_flash_models.reference_to_video` / `abra_r2v_<duration>s` qua RPC `MZZa6b`)**:
    - Đính kèm trực tiếp các thành phần tham chiếu (Ingredients): Khuôn mặt (`<Vlogger>` = ảnh mặt & tóc), Thân hình (`<Vlogger> Body` = body đã mặc hoàn chỉnh outfit, xem Rule 46), và Bối cảnh/Địa điểm/Đạo cụ (`reference_media_ids`). Video chỉ nhận Mặt + Body đã mặc outfit này, không cần nhận outfit riêng nữa.
    - Model `abra_r2v` tổng hợp trực tiếp chuyển động video mượt mà từ các thành phần tham chiếu và prompt, tích hợp khẩu hình native với voice profile **Laomedeia** (Slot 7).
    - Không chạy quy trình `GENERATE_IMAGE` cho từng cảnh; sau khi các entity có `media_id`, gửi thẳng yêu cầu `GENERATE_VIDEO_REFS`.
28. **Clean-Before-Video-Gen (Bắt buộc tẩy logo ảnh trước khi đưa vào sinh video)** — Đối với BẤT KỲ phân cảnh nào cần tạo ảnh Start Frame hoặc ảnh Reference từ Google Flow/AI (như cảnh vũ trụ, drone, phong cảnh thiên nhiên, hoặc start frame chuyển cảnh):
    - **TUYỆT ĐỐI KHÔNG dùng trực tiếp `media_id` do Google Flow tự sinh** để đưa thẳng vào sinh video. Ảnh AI của Google luôn tự chèn watermark logo ở góc dưới; nếu đưa thẳng vào i2v/r2v thì model video sẽ làm logo đó nhấp nháy, méo mó và dính chết vào video.
    - **Quy trình bắt buộc 4 bước đối với mọi ảnh do AI sinh**:
      1. Tải ảnh gốc về máy: `${OUTDIR}/images/scene_{idx}_{sid}.jpg`.
      2. Chạy ngay `python tools/remove_watermark_from_image.py "${OUTDIR}/images/scene_{idx}_{sid}.jpg"` để xóa sạch logo và SynthID ➔ sinh ra file `scene_{idx}_{sid}_clean.jpg`.
      3. Upload file sạch `scene_{idx}_{sid}_clean.jpg` ngược lên Google Flow qua `POST /api/flow/upload-image` để nhận một `media_id` UUID hoàn toàn sạch logo.
      4. Cập nhật `media_id` sạch này vào Scene (`horizontal_image_media_id` / `vertical_image_media_id`), đưa lên Review Board cho user duyệt. CHỈ SAU ĐÓ mới dùng `media_id` sạch này để sinh video!
29. **Confirm before every generation step (overrides the automatic parts of rules 16, 17, 19)** — Generation spends Flow credits, so:
    - **Before** any call that makes Flow generate media (`/fk-gen-refs`, `/fk-gen-images`, `/fk-gen-videos`, `GENERATE_*` / `REGENERATE_*` batches, test clips, retries, review-driven regens), state what will be generated and how many items, then **wait for the user's explicit yes**.
    - **After** each generation step finishes, STOP: show the results for review and wait for approval before starting the next stage (refs → videos → regens → concat).
    - Failures and low review scores are **reported, not auto-retried**: propose the fix (sanitized prompt, regen list) and ask before resubmitting.
    - Non-generating work (creating projects/scenes, uploading existing images, PATCHing fields, downloading, watermark removal) can proceed when the user asks for it.
30. **Vlog production lessons live in `/fk-time-travel-vlog` → `skills/fk-time-travel-vlog/references/production-lessons.md` (mục 11 cũ; prompt checklist ở `references/prompt-lock.md`)** (user feedback: constraints as sentences not `Negative:`, phone is the camera, wipes never make the vlogger vanish, scene refs for cities, landscape refs for 16:9, hardest clip first, `<Vlogger> Body` ref đã mặc hoàn chỉnh outfit (made per Rule 46), no `selfie-stick`/phone keywords to avoid ghost devices/screens, pure POV with empty hand, camera locked in hand for run/jump action physics, single-arm vlog holding to prevent dual-arm glitch, crowd fleeing forward with vlogger away from disaster, anti-CGI documentary anchors for disaster scenes, ground anchor timber barrier force transmission `force -> barrier -> ground` instead of human boots/body, megafauna momentum p=m*v with secondary ear/trunk lag and ice traction-loss sideways deflection instead of ABS instant stops, thermodynamic localized bubbling and radiating cracks before bone fracture, material deformation like hide flexing under needle and vibrating drum membrane, rapid vapor dissipation in freezing cold, natural smartphone perspective instead of rigid zero-distortion, running camera with footfall vertical bounce and rotational lag, 5-layer prompt architecture, physical prop continuity, permanent arm & camera lock in leap/slide action shots to prevent phone dropping and 3rd-person spectator switches, reference ingredients hierarchy [Face -> Body -> Outfit] and negative contrast constraints against mannequin body drift). Follow them for every POV/vlog project.
31. **On any pipeline error** (request `FAILED`, stuck `PROCESSING`, `extension_connected: false`, HTTP 4xx/5xx from `:8100`, YouTube `HttpError`, error strings like `UNSAFE_GENERATION` / `not found` / `CAPTCHA` / `NO_AT_TOKEN` / `NO_FLOW_PROJECT` / `UNSUPPORTED_ON_BATCH_API`): invoke `/fk-doctor` before guessing a fix.
32. **AI-First Video Review before User Approval & Conditional Upscale (Tự động review trên video 720p thô ➔ Duyệt ➔ Upscale 1080p & Xóa Logo)** — Sau khi video 720p hoàn tất và tải về máy, Agent trích xuất frames trực tiếp từ video 720p thô (chưa cần xóa logo), tự động chạy phân tích `/fk-review-video` trước: chấm điểm theo 6 tiêu chuẩn cốt lõi (Character Consistency 25%, Prompt Adherence 20%, Motion Quality 20%, Visual Fidelity 15%, Temporal Coherence 10%, Composition 10%), rà soát lỗi AI (Critical/High/Minor), và trình bày bảng Scorecard chi tiết kèm ảnh preview frames cho User xem trước. **Chỉ khi User duyệt thông qua cảnh**: Mới tiến hành gửi batch Upscale 1080p và xóa logo trên video 1080p.
33. **Standard 16:9 Character Turnaround Sheet (Chuẩn 4 góc khóa nhận diện & trang phục)** — Mọi ảnh reference cho nhân vật (cả nhân vật chính vlogger lẫn nhân vật phụ bản địa) BẮT BUỘC phải tạo dưới dạng **Character Sheet 16:9 chuẩn 4 góc (Turnaround Sheet)**: (1) Toàn thân chính diện (Full-body front view): Thấy rõ 100% trang phục may đo thời kỳ từ đầu đến chân (áo, quần, giày/ủng tuyết, phụ kiện, vũ khí/dụng cụ cầm tay), (2) Toàn thân 3/4 (Full-body 3/4 view): Thể hiện độ dày phom dáng, mũ trùm/áo choàng, độ rủ của chất liệu, (3) Toàn thân nhìn nghiêng (Full-body side profile): Thể hiện tư thế cầm nắm và cấu trúc trang phục cản gió, (4) Cận cảnh chân dung khuôn mặt 16:9 (Portrait close-up): Thấy rõ từng chi tiết khuôn mặt gốc (ánh mắt, sống mũi, kết cấu da chân thực, tóc và viền cổ áo/nón lông). Giữ nguyên nhận diện khuôn mặt (Identity Consistency) từ ảnh gốc người dùng cung cấp nhưng đồng bộ trang phục bối cảnh lịch sử chuẩn xác.
34. **Architectural & Prop Reference Cleanliness (Cấm người đo tỉ lệ & Cấm chia đôi khung hình)** — Khi sinh ảnh reference cho công trình kiến trúc (như lều xương voi ma mút Mezhirich, kim tự tháp, đền đài, thành lũy) hoặc sinh vật/đạo cụ: TUYỆT ĐỐI KHÔNG dùng các cụm từ gây nhiễu như "with proper scale reference" khiến AI vẽ thêm người đứng đo, thước đo tỉ lệ hoặc thanh đo khảo cổ học. BẮT BUỘC chỉ định: `ONE single unified photograph only, strictly NO humans, NO people, NO scale figures, NO measuring rods, NO split screen, NO multi-panel comparison`.
35. **Historical Clothing Scientific Authenticity (Trang phục tiền sử may đo nhiều lớp)** — Kỷ Băng Hà (20,000 BC - LGM / Gravettian): Con người BẮT BUỘC phải mặc quần áo may đo nhiều lớp ôm sát (*tailored layered clothing*: áo parka chui đầu da tuần lộc, lót len lông mammoth wool, viền lông cáo tuyết chống đọng băng, quần da bó, ủng bọc lông, thêu hạt ngà voi). Tuyệt đối không vẽ người tiền sử cởi trần hoặc quấn da thú thô sơ phi thực tế giữa thảo nguyên băng giá -35°C đến -45°C.
36. **Translator POV Interaction (Kỹ thuật Vlog Phiên Dịch — Giao tiếp với người bản địa)** — Do AI video model (Omni Flash / Veo 3) chỉ nhận 1 giọng nói duy nhất (Slot 7 Laomedeia) và để bảo tồn tính chân thực lịch sử (thổ dân tiền sử/cổ đại không nói tiếng Anh hiện đại), TUYỆT ĐỐI KHÔNG gán thoại tiếng Anh cho nhân vật phụ (`Torak says: "..."`). Thay vào đó: (a) Nhân vật phụ giao tiếp bằng cử chỉ tay, biểu cảm sống động, hiệu lệnh săn bắn hoặc cổ ngữ tự nhiên trong phần prompt hành động (`Torak urgently gestures...`), (b) Vlogger đóng vai trò cầu nối phiên dịch: lập tức xoay camera về phía mình (Selfie 0.5x hoặc handheld whip pan) và thuật lại trực tiếp cho khán giả (`Nora says: "Torak warned us that...", "She told me this is..."`).
37. **Permanent Arm & Camera Lock in Action/Leap Shots (Cấm buông máy hoặc chuyển góc người thứ 3 khi nhảy/tiếp đất/trượt dốc)** — Khi mô tả vlogger nhảy qua gờ dốc, tiếp đất hoặc trượt tuyết trong shot vlog selfie, AI video model có xu hướng cho nhân vật buông tay giữ thăng bằng và tự động lùi máy ra thành góc nhìn người thứ ba (spectator wide shot). BẮT BUỘC: (a) Khóa cứng cánh tay và máy quay bằng câu khẳng định vĩnh viễn (`her [right] arm remains permanently extended gripping the camera tightly aimed directly back at her screaming face; she NEVER drops, releases, or lets go of the camera, and the view NEVER switches to third-person`), (b) Tả chấn động quán tính lên khung hình và mặt đất/tuyết bay (`view jerks violently downward with the drop`) thay vì tả chuyển động toàn thân (`she slides/leaps`), giữ mặt vlogger luôn neo chặt ở trung tâm khung hình selfie.
38. **Reference Ingredients Order & Negative Contrast Body Lock (Thứ tự truyền Ref [Mặt -> Body đã mặc outfit] & Khóa tương phản chống Body Drift)** — BẮT BUỘC: (a) Server gửi ref ingredients theo đúng thứ tự nhận diện: `[Face] -> [Body]` (ví dụ: `["Nora", "Nora Body"]` trong đó `Nora Body` đã là ảnh body mặc hoàn chỉnh trang phục, xem Rule 46). Không cần entity outfit riêng lẻ, (b) Trong `common.identity` và `video_prompt` phải bổ sung cụm từ tương phản đối kháng mạnh mẽ ép model tôn trọng đường cong: `BODY LOCK (CRITICAL): [Character] has a voluptuous hourglass figure with large full heavy natural bust, tiny narrow waist, and wide curvaceous hips matching Body ref; she is NOT skinny, NOT slender, NOT petite, NOT flat-chested`.
39. **Early Conditioning Prompt Architecture & Stature/Cleavage Punch (Đưa Body Lock lên sớm, góc máy hất nhẹ & đấm lực tôn dáng)** — Để vòng 1 không bị nhỏ và chân không bị ngắn trong video selfie chuyển động: (a) **Vị trí Body Lock trong Prompt**: BẮT BUỘC đưa khối `Identity & Body Lock` lên vị trí SỚM ngay sau `Shot:` (trước các phân đoạn hành động `0-3s`, `3-6s`), không chôn vùi ở cuối prompt dài 5.000 ký tự gây suy giảm chú ý (attention decay), (b) **Góc máy quang học (Low-Angle Chest Level)**: Trong `style.run` và `style.selfie`, chỉ định camera đặt ngang ngực/bụng trên hơi hất nhẹ lên (`held at chest/mid-torso level angled slightly upward looking back`) thay vì ngang mặt chúc xuống, loại bỏ co ngắn phối cảnh (foreshortening), kéo dài đôi chân và khoe trọn khe ngực, (c) **Cú đấm lực vòng 1 & chân siêu mẫu**: CẤM các từ `low-hanging bust`, `natural bust compression` hay `thick thighs` đơn độc. Dùng cụm đối kháng cực mạnh: `exceptionally large, full, voluminous heavy bust pushed up with prominent deep cleavage valley spilling out of the plunging V-neckline (dramatic push-up cleavage effect, huge voluptuous cleavage)`, và thông số chiều cao `tall, statuesque woman (178 cm / 5'10" tall) with exceptionally long, slender model legs and high hip placement`, (d) **Gia cố trong Action Segments**: Lặp lại trực tiếp đặc điểm thể hình vào các hành động chuyển động trong từng mốc thời gian (`her long slender legs pumping powerfully through snow; her voluminous bust with dramatic push-up cleavage bouncing in plunging neckline`).
40. **The 4 Physical Principles of Survival POV Action & Optical Viewpoint (Bộ tứ nguyên lý vật lý sinh tồn & Cấm triệt để từ 'phone/smartphone' kèm Self-Linter)** — Mọi cảnh hành động, chạy trốn, té ngã trong POV Vlog BẮT BUỘC tuân thủ: (1) **Động lượng & Quán tính cơ học ($p = m \\cdot v$)**: Vấp rãnh băng mất ma sát $\\mu \\to 0$, thân trên lao về phía trước, loạng choạng 1-2 bước cứu thăng bằng trước khi trọng lực $F_g = mg$ đè sụp ngã đập người nén tuyết; cấm nhảy lơ lửng chống trọng lực. (2) **Tương phản Trọng tải trên Sườn dốc ($m_{\\text{voi}} \\gg m_{\\text{người}}$)**: Bờ dốc sông băng $\\theta = 45^\\circ-60^\\circ$ biến cú ngã thành cú trượt cày tuyết xốp an toàn ($F = mg\\sin\\theta - \\mu mg\\cos\\theta$); thú lớn 6 tấn không dám lao xuống vì sợ sạt lở gãy chân, giải thích logic sinh tồn tại sao vlogger thoát chết. (3) **Điểm mù Quang học & Động học Camera**: Người xem nhìn trực tiếp qua ống kính (`camera lens`), máy quay và tay cầm máy nằm ở điểm mù sau mặt phẳng tiêu cự (`completely off-screen and never seen`), tay tự do trống không (`empty hand`). TUYỆT ĐỐI CẤM 100% các từ `phone`, `smartphone`, `screen`, `device`, `selfie-stick` (kể cả trong câu cấm 'never drops the phone'); va đập làm máy giật nảy (`rotational jolt`) và tuyết bột phủ mờ thấu kính (`lens glass splatter`). (4) **Biến dạng Vật liệu & Triệt tiêu Động năng**: Nứt nén bề mặt băng tuyết (`crust fracture`), hất tung bụi tuyết khí dung (`aerosolized powder snow`), và rãnh ma sát sâu (`frictional furrow`) triệt tiêu dần động năng $\\frac{1}{2}mv^2 \\to Q$. BẮT BUỘC chạy Prompt Self-Linter (`python tools/lint_prompt.py`) tự kiểm tra sạch sẽ từ cấm trước khi gửi gen.
41. **No Behind-the-Head 3rd-Person Shots & Camera Materialization Glitch (Cấm quay sau đầu chuyển selfie & Cấm biến camera thành đạo cụ)** — (1) **Tuyệt đối cấm shot sau đầu/sau lưng**: TUYỆT ĐỐI CẤM các câu lệnh quay từ sau đầu hoặc sau lưng vlogger rồi xoay ra trước mặt (`starts from behind her head then turns to face her`). Góc quay sau lưng là góc nhìn NGƯỜI THỨ BA (3rd-person spectator); AI thấy vlogger từ phía sau sẽ tự hỏi tay cô đang giơ cái gì lên và lập tức "vật thể hóa" thành một chiếc máy ảnh kỹ thuật số (compact camera có màn hình LCD) hoặc ống kính máy ảnh rời (DSLR Lens) cầm trên tay. (2) **Đơn góc nhìn thay thế hoàn toàn Whip Pan (xem Rule 42)**: TUYỆT ĐỐI KHÔNG dùng cú lia máy 180° giữa cam trước và cam sau trong cùng 1 shot liên tục. Để quay vlogger tương tác với môi trường/nhân vật phía sau, BẮT BUỘC dùng **100% Selfie Qua Vai (Over-the-Shoulder)** hoặc **Cặp Shot Kép cắt cảnh riêng biệt (Two Separate Cuts)**. (3) **Cấm mô tả cầm camera làm đạo cụ**: Không bao giờ viết `she holds/brings the camera around`; thay bằng `she pivots her extended arm back toward herself`. Điểm nhìn người xem chính là thấu kính (`camera lens`).
42. **Single-Perspective Vlog Purity, No 180° Camera Flips & The Golden Camera Ratio (Quy tắc đơn góc nhìn thuần khiết, Cấm xoay lật 180° & Tỷ lệ góc máy vàng)** — (1) **Nghịch lý lật cam 180°**: Trong vlog thực tế bằng điện thoại, không ai vừa quay cam sau (quay người khác/cảnh vật) lại lật ngược 180° điện thoại để tự quay mặt mình trong cùng 1 shot liên tục, vì màn hình điện thoại bị quay đi hướng khác (người quay bị mù màn hình), và camera tự bay vòng 180° trong không khí tạo cảm giác giả tạo như có người quay phim thứ 3 (cameraman cầm gimbal/flycam) bay quanh nhân vật. (2) **Quy tắc Vàng 1 Shot = 1 Góc nhìn**: Mỗi shot 8s–10s BẮT BUỘC giữ duy nhất MỘT góc máy cố định: hoặc 100% Selfie (Cam trước 0.5x), hoặc 100% First-Person POV (Cam sau). TUYỆT ĐỐI CẤM các cú lia máy lật xoay 180° (`whip pan 180-degree ... turning to face`, `pivoting the viewpoint back`). (3) **Kỹ thuật Vlog Selfie qua vai (Over-the-Shoulder Selfie Interaction)**: Khi vlogger tương tác hoặc giới thiệu nhân vật phụ (như Torak, thổ dân, quái thú): vlogger chiếm 1/3 tiền cảnh ở một bên (selfie góc rộng 0.5x), nhân vật phụ xuất hiện ở 2/3 hậu cảnh phía sau vai vlogger. Tương tác được thực hiện tự nhiên qua việc vlogger nói với khán giả, khẽ liếc mắt hoặc quay đầu ra sau kiểm tra đối tượng, rồi quay lại nhìn thẳng vào camera thì thầm/thể hiện cảm xúc. Khung hình luôn neo chắc vào vlogger, chuyển động camera chỉ là rung lắc bước chân tự nhiên, đảm bảo tính chân thực 100% của một POV travel vlog. (4) **Tỷ lệ Góc Máy Vàng trong POV Vlog (Golden Camera Ratio — Chống đơn điệu 100% Selfie)**: Một video vlog chân thực KHÔNG THỂ 100% các cảnh đều giơ tay selfie dí sát mặt vlogger. Tỷ lệ phân bổ chuẩn mực: **60%–70% First-Person POV qua mắt vlogger (Cam sau)** (dành cho toàn bộ cảnh hành động, khám phá, di chuyển, rình mò, săn bắt, chế tác công cụ, thao tác 2 tay, quan sát đồng đội và cảnh vật); **20%–30% Front-Camera Selfie & Over-the-Shoulder (Cam trước 0.5x)** (dành cho lúc an toàn, chia sẻ tâm sự trực diện, mở đầu/kết thúc, phản ứng biểu cảm sau nguy hiểm); **10% Ground / Fixed Cam** (máy tựa đá/đất cho thao tác 2 tay rảnh). TUYỆT ĐỐI CẤM liên tiếp 3 cảnh cùng góc selfie quay mặt vlogger!
43. **Temporary & Debug Scripts in Scratch Directory Only (Tất cả script tạm/debug/test bắt buộc lưu trong `scratch/`)** — Mọi script tạm thời, one-off script để test prompt, debug API, test chức năng, kiểm tra trạng thái hoặc setup tạm (như `test_*.py`, `check_*.py`, `setup_*.py`, `debug_*.py`, `patch_*.py`) TUYỆT ĐỐI KHÔNG được tạo trong các thư mục mã nguồn của dự án (như `scripts/`, `tools/`, hoặc thư mục gốc repo `c:/flowkit/`). BẮT BUỘC chỉ được tạo trong thư mục artifact scratch của cuộc hội thoại (`<appDataDir>/brain/<conversation-id>/scratch/` hoặc chạy inline one-liner `python -c "..."`). Sau khi hoàn tất mục đích debug/test, phải dọn dẹp sạch sẽ để giữ codebase repo luôn sạch, chuẩn và chuyên nghiệp.
44. **Inter-Scene Posture & Gaze Continuity (Khớp tư thế & hướng nhìn giữa 2 shot liền kề — Match on Action)** — (1) **Lỗi giật tư thế (Posture Snap)**: Khi Clip A kết thúc ở một tư thế cụ thể (như quay đầu nhìn bối cảnh, tay chỉ hướng, hoặc nghiêng người), nếu Clip B mở đầu ngay bằng tư thế đứng thẳng nhìn vào camera thì khi ghép nối sẽ tạo ra cú cắt giật (jump cut) làm gãy mạch thị giác. (2) **Quy tắc Khớp Động Tác (Match on Action Continuity)**: Clip B BẮT BUỘC phải mở đầu ở đúng tư thế kết thúc của Clip A trong 1–2 giây đầu (`0-2s: Matching the previous scene's ending, the clip opens with her head turned looking back over her shoulder...`), sau đó mới mô tả nhân vật chuyển đổi tư thế (nhận ra đối tượng, xoay mặt lại nhìn vào camera) ngay trong shot. Điều này biến mối nối giữa 2 clip AI thành một chuyển động liên tục tự nhiên như phim điện ảnh.
45. **Camera-Touch Prevention & Functional Prop Dressing Physics (Chống với tay chạm ống kính & Khóa hành vi mặc/đeo đạo cụ chức năng thực tế)** — (1) **Chống với tay lên ống kính / màn hình (Camera-Touch Glitch)**: Trong các shot vlog selfie hoặc tương tác, AI thường nhầm lẫn giữa việc "giơ tay khoe đồ / diễn đạt cảm xúc" với việc "đưa tay chạm vào ống kính / chọt màn hình điện thoại", gây che khuất khung hình, méo tay cận ống kính và làm lộ điện thoại (Camera Materialization). BẮT BUỘC: Khóa cứng vị trí bàn tay tự do ở ngang ngực hoặc cách xa ống kính: `"Nora holds her free hand up at chest level showing the item to the camera at a safe distance; her free hand NEVER reaches toward, touches, covers, taps, or points at the camera lens; her selfie arm remains steady holding the camera at a constant distance"`. (2) **Khóa hành vi mặc/đeo đạo cụ chức năng thực tế (Functional Prop Dressing & Equipment Transfer)**: Khi một nhân vật trao hoặc mặc đồ bảo hộ/trang phục/phụ kiện cho nhân vật khác (như găng tay/bao tay lông thú, áo choàng, mũ nón, ủng tuyết, thắt lưng, kính tuyết, vòng cổ): AI thường chỉ cho nhân vật phụ cầm dây buộc/sợi dây lủng lẳng hoặc đưa hờ hững trước mặt mà KHÔNG HỀ xỏ găng/mặc áo vào cho nhân vật chính. BẮT BUỘC: Prompt phải mô tả trực tiếp ĐỘNG TÁC XỎ / MẶC CHỨC NĂNG bằng các động từ hành động cụ thể (`slips and slides directly onto`, `fits securely over`, `pulls over`, `fastens onto`): `"[Character A] attentively holds the [prop/garment] and actively slips and slides it directly onto [Character B]'s [bare hand/body], fitting it completely on before fastening any cords; [Character B] physically wears the [prop] on her [hand/body], feeling its fit and warmth"`. TUYỆT ĐỐI KHÔNG chỉ viết chung chung `"gives mittens and ties cords"` vì model sẽ chỉ vẽ sợi dây mà bỏ qua hành động mặc/xỏ găng thực tế. (3) **Đồng bộ chuyển động giữa 2 nhân vật (Synchronized Handover in POV)**: Phân đoạn thời gian rõ ràng: 0–3s (Nhân vật A trực tiếp xỏ/mặc đạo cụ vào người nhân vật B), 3–6s (Nhân vật B nhận, đạo cụ đã được mặc hoàn chỉnh trên cơ thể, giơ lên ngang ngực khoe với camera), 6–8s (Thể hiện cảm xúc, tương tác ánh mắt cảm ơn giữa hai nhân vật, kiểm tra độ ấm/vừa vặn của đạo cụ).
46. **Body Đã Mặc Trang Phục Làm <Vlogger> Body; Video Nhận Mặt + Body, Không Cần Nhận Outfit Riêng (user lock 2026-10-05)** — (1) **<Vlogger> Body BẮT BUỘC là Body đã mặc hoàn chỉnh trang phục**: Trong mọi dự án video nhân vật/vlog, nhân vật chỉ có đúng 2 ref chính: `<Vlogger>` (Khuôn mặt & tóc) và `<Vlogger> Body` (Body đã mặc trang phục). TUYỆT ĐỐI KHÔNG tạo entity `<Vlogger> Outfit` riêng lẻ gây thừa thãi và phân mảnh. Quy trình tạo `<Vlogger> Body`: Dùng ảnh Body trần làm nguồn (`source_media_id`), chạy `EDIT_CHARACTER_IMAGE` với prompt mô tả trang phục vừa vặn form-fitting để "mặc đồ" lên body đó: giữ nguyên 3 panel (chính diện, 3/4, sau lưng), tư thế, tỷ lệ cơ thể (ngực, eo, hông, chân), khung cắt vai/dưới cằm không lộ mặt, và nền studio. Sau khi sinh xong, xóa logo, upload ảnh sạch và gán trực tiếp làm `media_id` cho `<Vlogger> Body`. Video R2V sẽ chỉ nhận: `[<Vlogger>, <Vlogger> Body, <Bối cảnh/Đạo cụ>]`. (2) **Cổng Duyệt Body Đã Mặc Trang Phục Bắt Buộc (Mandatory Dressed Body Approval Gate)**: Trước khi gửi bất kỳ lệnh sinh video nào (`GENERATE_VIDEO_REFS` / `GENERATE_VIDEO`), Agent BẮT BUỘC phải xuất ảnh Body đã mặc trang phục sạch watermark, hiển thị cho User xem và **CHỜ USER DUYỆT THÔNG QUA FORM DÁNG & TRANG PHỤC**. Tuyệt đối KHÔNG được tự ý gửi lệnh sinh video khi User chưa xác nhận và duyệt. (3) **Khóa mô tả Body & Outfit trong Prompt (`[ID-LOCK]`)**: Khối `[ID-LOCK]` trong mọi prompt cảnh video (`video_prompt`) BẮT BUỘC phải đối chiếu và mô tả đồng nhất chuẩn xác: khuôn mặt từ `<Vlogger>`, vóc dáng và trang phục lấy từ `<Vlogger> Body` đã duyệt.
47. **Ironclad Identity & Body-Outfit Locking in R2V (Quy tắc khóa chuẩn nhận diện Tóc, Body Đã Mặc Trang Phục và loại trừ Body-Contamination trong R2V)** — (1) **Bộ Reference tối ưu (Tối đa 3 Ref)**: Khi sinh video R2V qua Omni Flash Ingredients (`GENERATE_VIDEO_REFS`), danh sách `character_names` cho cảnh có Vlogger BẮT BUỘC chỉ gồm `[<Vlogger>, <Vlogger> Body, <Creature/Asset>]` (trong đó `<Vlogger> Body` đã là ảnh Body mặc trang phục hoàn chỉnh theo Rule 46). **TUYỆT ĐỐI KHÔNG đưa ảnh Body trần/gym chưa mặc đồ** vào bất kỳ cảnh video nào, vì ảnh Body gym (áo tank top sát nách + quần đùi lộ da tay chân trần) sẽ gây nhiễm latent da thịt (Body Latent Contamination), ép model AI biến trang phục thành đầm da thú cộc tay cởi trần kiểu người tiền sử generic. Không cần entity Outfit riêng lẻ. (2) **Ảnh Body 3 góc = Body đã mặc outfit (Rule 46)**: `<Vlogger> Body` phải liên kết với ảnh Body sheet đã mặc outfit 3 góc sạch logo có đầy đủ chi tiết mũ trùm lông cổ vai to bản, dây đan ngực, thắt lưng, viền lông gấu áo, quần legging và bốt cao cổ. (3) **Cấm bẫy prompt trống (The Empty Prompt Trap)**: TUYỆT ĐỐI KHÔNG xoá sạch mô tả outfit và tóc trong prompt rồi chỉ để câu logic trỏ `wearing the exact outfit from reference image`. Diffusion model không hiểu câu logic này; khi thiếu từ khoá thị giác neo giữ (visual anchor tokens), từ khoá bối cảnh thời kỳ sẽ ép nhân vật thành tóc bù xù xoã ngang vai và áo da thú cởi trần nguyên thủy. (4) **Khối Prompt Khóa Bắt Buộc**: BẮT BUỘC đưa khối `IDENTITY & OUTFIT LOCK (CRITICAL)` lên vị trí SỚM ngay sau `Shot:` trước `0-3s`, mô tả chuẩn xác: màu tóc, kiểu cột cao có mái bay (`honey-blonde hair tied in a high wavy ponytail with curtain bangs framing her face, bouncing energetically with each running stride`), chi tiết vóc dáng và trang phục đầy đủ từ ảnh `<Vlogger> Body`, và câu phủ định đối kháng cực mạnh (`This outfit is GOLDEN-TAN throughout -- NOT dark, NOT brown, NOT a caveman fur pelt, NOT sleeveless, NOT bare legs, NOT loose unkempt hair, NOT modern clothing`). Nhắc lại chuyển động của tóc đuôi ngựa và tà áo/bo lông trong từng phân đoạn `0-3s`, `3-6s`.
48. **High-Retention Survival Pacing & The Action Hunting Pivot (Cấm bẫy lãng nhác một mình, Đời sống cô đọng & Bắt buộc kích hoạt Cuộc đi săn để giữ Retention)** — (1) **Cấm bẫy nhân vật ngồi lãng nhác một mình (No Idle Isolation Trap)**: Sau khi vượt qua thử thách bước vào nơi trú ẩn (hang đá, ngôi làng), TUYỆT ĐỐI CẤM để nhân vật chính ngồi một mình trơ trọi hơ lửa/ngắm cảnh/làm việc thụ động kéo dài gây tụt cảm xúc và gãy nhịp phim (killing emotional momentum & drop retention). Mọi cảnh sưởi ấm/nghỉ ngơi BẮT BUỘC phải gắn liền với tương tác đùm bọc cộng đồng (người bản địa trùm da thú che chở, kéo vào lòng bếp) hoặc hành động cứu sinh mệnh có mục đích (cấp cứu hạ thân nhiệt bằng đá nung stone-boiling). (2) **Nguyên tắc "Đời sống cô đọng" (Compact Hearth Life — Tối đa 5–7 cảnh / ~1 phút)**: Toàn bộ sinh hoạt nội trú (bếp lửa, chế tác công cụ, nấu nướng) BẮT BUỘC phải cô đọng, sắc nét; cấm bôi lan man 15–30 cảnh biến video thành phim tài liệu bảo tàng thủ công mỹ nghệ. Cấm lặp lại chi tiết vụn vặt (đã sờ trang phục thì không lặp lại so sánh mũi khâu; đã nạo da thì không thêm cảnh cơ bắp nạo da). (3) **Bắt buộc kích hoạt Cuộc Đi Săn / Cao trào Sinh Tồn (The Action Hunting Pivot — Goal Chaining)**: Ngay sau khi hồi phục thân nhiệt (mục tiêu A xong), BẮT BUỘC xuất hiện ngay nhu cầu sinh tồn sống còn mới theo chuỗi nhân quả: Kho thịt cạn kiệt, bão tuyết sắp tới, nhóm phải xuất quân đi săn thú lớn thời Băng Hà (Steppe Bison, Mammoth, Tuần lộc). Nhân vật chính chủ động xin gia nhập đoàn săn để chứng minh giá trị, không làm gánh nặng. (4) **Nhân quả liền mạch kéo sang Cao trào Đêm (Causality Bridge to Act 4)**: Đưa nhân vật ra khỏi vùng an toàn bước vào cuộc săn nghẹt thở: lần dấu tuyết -> phục kích áp sát bằng giáo đâm -> quái thú lồng lộn phản kháng -> đòn kết liễu phối hợp -> xẻ thịt thần tốc giữa gió tuyết. Mùi máu tươi từ cuộc săn ngoài thảo nguyên là nguyên nhân trực tiếp kích hoạt bầy thú dữ (Linh cẩu, Sói) bám đuôi về hang, dẫn thẳng vào trận tử thủ đêm bão tuyết (kết nối hoàn hảo với Cold Open).
49. **Golden Standard Dialogue for 8s POV Vlog Clips & Sonic Isolation Hunting Exception (18 đến 22 từ / Clip 8s & Ngoại lệ im lặng khi săn bắn/ẩn nấp)** — (1) **Định lượng từ chuẩn 18 – 22 từ (Hard Constraint: 18 - 22 words per 8s clip)**: Clip 8s dùng lệnh `-ss 1` trim 1 giây đầu (khử giật AI) ➔ video hữu dụng thực tế = 7.0s. Trừ buffer đệm 0.5s an toàn ➔ thời lượng phát âm tối đa = ~6.5s. Tốc độ đọc tự nhiên (Laomedeia / TTS 1.1x - 1.2x): ~3.2 – 3.5 từ/giây. Dưới 18 từ: Gặp lỗi **Dead Air** (khoảng lặng chết, video thừa hình nhân vật im lặng làm tụt retention). Trên 22 từ: Gặp lỗi **Cut-off** (tràn thời lượng sang cảnh sau, câu nói bị ngắt cụt giữa chừng). BẮT BUỘC 100% các câu thoại trong các cảnh trò chuyện/vlog bình thường (cả tiếng Anh `narrator_text` và tiếng Việt Vietsub) phải nằm chuẩn trong dải **18 đến 22 từ**. (2) **Phân bổ cấu trúc 3 phân đoạn thời gian (0-3s, 3-6s, 6-8s)**: `0-3s` (6–7 từ: Cảm giác / Phản xạ ban đầu / Thiết lập bối cảnh), `3-6s` (7–8 từ: Miêu tả hành động / Diễn biến chính), `6-8s` (5–7 từ: Cảm xúc đọng lại / Cú punchline kết cảnh). (3) **Khóa liên kết kỹ năng (Skill Interlock — Mandatory fk-gen-narrator Integration)**: Mọi skill viết kịch bản POV vlog (`time-travel-vlog`, `fk-time-travel-vlog`, `fk-vlog-guide`) KHI VIẾT THOẠI BẮT BUỘC phải tuân thủ và khóa trực tiếp các tiêu chuẩn của `fk-gen-narrator`. Lời thoại phải được nhúng trực tiếp vào prompt theo thời gian thực (`Nora whispers "..."`, `Nora says "..."`) và đồng bộ vào `narrator_text`. (4) **Ngoại lệ Sinh tồn & Rình săn: Sonic Isolation (Im lặng tuyệt đối khi rình mồi & hành động sinh tử)**: Ngoại lệ bắt buộc duy nhất cho quy tắc 18–22 từ là **các cảnh rình rập, áp sát thú dữ, ẩn nấp, hoặc giao chiến sinh tử một mất một còn**. Khi cách dã thú 3 mét, vlogger TUYỆT ĐỐI KHÔNG mở miệng nói chuyện (phản logic sinh tồn). Trong các cảnh này: BẮT BUỘC áp dụng kỹ thuật **Sonic Isolation** (`Strictly NO spoken dialogue. Her mouth stays firmly closed; she holds her breath in dead silence`). Căng thẳng được thể hiện qua âm thanh vật lý Foley (tiếng thở gấp nén chặt qua mũi, tiếng tim đập dồn, tiếng cành gãy, tiếng thú thở phì phò). Lời dẫn/suy nghĩ nội tâm nếu có sẽ được chèn ở **hậu kỳ voiceover/subtitles**, miệng nhân vật trong video KHÔNG ĐƯỢC mấp máy!
50. **Mandatory Upstream Cinematic Skills Interlock in Time-Travel Vlog (Khóa cứng bắt buộc 7 skill điện ảnh & hành động vào Time-Travel Vlog — CẤM TUYỆT ĐỐI BỎ SÓT)** — (1) **Nguyên tắc khóa cứng không thể phá vỡ**: Khi thực hiện bất kỳ dự án POV/Time-Travel Vlog nào (`/fk-time-travel-vlog`, `/fk-vlog-guide`, `/fk-vlog-japan`), AI Agent BẮT BUỘC phải áp dụng đồng bộ và nghiêm ngặt 7 skill điện ảnh đã tích hợp trong `references/cinematic-toolkit.md`. TUYỆT ĐỐI CẤM bỏ qua hoặc làm tắt:
    - **`/fk-action-choreography` (§1)**: Mọi cảnh hành động, săn bắn, giao chiến, chạy trốn, ngã, hoặc thao tác dùng 2 tay BẮT BUỘC dùng **First-Person POV qua mắt vlogger** hoặc **Camera dựng cố định / nấp sau vật cản**. CẤM 100% việc vlogger vừa đi săn vừa giơ tay selfie quay mặt mình. Phải chia đúng **3 pha hành động** (`0-3s` Chuẩn bị -> `3-6s` Một đòn duy nhất dứt khoát theo hướng -> `6-8s` Thu thế & chấn động dội ngược). Dùng từ vựng an toàn chống méo người (thú lao chéo góc, đất mùn tung tóe, không tả xuyên thịt/máu me).
    - **`/fk-scriptwriter` (§2–3)**: **ĐỔI CỠ CẢNH LIÊN TỤC** — CẤM TUYỆT ĐỐI 2 cảnh liền nhau cùng 1 góc máy/cỡ cảnh. Phải xoay vòng: POV rộng -> POV chi tiết tay -> POV quay lén từ chỗ nấp -> Selfie qua vai (Over-the-shoulder) -> Máy dựng cố định. Thể hiện cảm xúc bằng triệu chứng cơ thể (thở dốc, bấu chặt ngón tay, mắt đảo), không dùng tính từ trừu tượng. Kỹ thuật hồi hộp: Blind spot, Sonic isolation (im lặng nghẹt thở khi rình mồi / rình săn), Deceptive calm.
    - **`/fk-character-bible` (§4–5, Rule 46, Rule 47)**: Khóa cứng `OUTFIT LOCK (Anti-Tank Top Lock)`: Tunic dài tay, đai corset, quần da ôm sát, ủng cao cổ. CẤM triệt để áo ba lỗ/tank top/gym sportswear hiện đại lọt vào thời tiền sử/cổ đại.
    - **`/fk-camera-guide`**: Cấu trúc 5 lớp vật lý, quang học smartphone tự nhiên (camera ngang ngực, rung nảy bước chân), cấm camera tự bay lượn như flycam/gimbal.
    - **`/fk-sound-design` (§6)**: Hậu kỳ âm thanh — Ducking nhạc nền tự động theo track thoại, master chuẩn YouTube -14 LUFS / -1 dBTP, layering SFX tiếng va chạm/tiếng tim đập.
    - **`/fk-cinematic-transitions` (§7)**: Kỹ thuật J-cut khi cắt thẳng, không dùng bumper/crossfade/dip-to-black làm mất cảm giác footage chân thực.
    - **`/fk-capcut-edit` (`scripts/trailer_cuts.py`)**: Tạo hook montage / intro trailer tự động qua 2 bước scan loudness/motion và build timeline.
    (2) **Cổng kiểm tra trước khi sinh (Prompt Pre-Generation Gate)**: Mọi `video_prompt` trước khi lưu vào DB hoặc gửi gen BẮT BUỘC phải đối chiếu qua Bảng Checklist B của `prompt-lock.md`. Nếu vi phạm (ví dụ: cảnh săn thú mà dùng selfie nói chuyện, 2 cảnh liền kề cùng góc máy, thiếu outfit lock, hoặc bối cảnh phủ tuyết sai lệch) -> BẮT BUỘC SỬA PROMPT TRƯỚC, KHÔNG ĐƯỢC GỬI SINH!
51. **Zero Melee Combat / Realistic Vlog Camera Direction (Self-Vlog + Two-Handed In-Frame Experience) & 23–25 Word Rapid Delivery (Cấm 100% giáp lá cà, Phối hợp Tự quay + Khung hình trải nghiệm 2 tay & Thoại nhanh 23–25 từ — User Lock 08/10/2026)** — (1) **Cấm 100% cảnh đánh đấm / vật lộn cận chiến với thú lớn**: AI video model (Veo 3 / Omni Flash R2V) bị quá tải cơ học tiếp xúc (contact physics) dẫn đến méo vũ khí, quái thú trượt lướt mất trọng lực và vỡ giải phẫu người khi có va chạm giáp lá cà. TUYỆT ĐỐI KHÔNG viết các cảnh đâm giáo, bò húc, vật lộn cận chiến. (2) **Chuyển sang POV Phone-Vlog Giao Lưu & Cơ Chế Sinh Tồn Kỳ Thú**: Học hỏi công thức thành công của các kênh triệu view (như Medieval Sisters) nhưng giữ nguyên bản sắc Vlog. Kịch bản tập trung vào Nora đến giao lưu văn hóa, học hỏi và trải nghiệm sinh tồn thực tế (đẽo đá Mousterian sắc như dao mổ, may đo chỉ gân hươu, đun sôi nước bằng đá nung trong âu da, bột khoáng xúc tác MnO2, dấu bàn tay đất son đỏ). (3) **Quy tắc phối hợp Góc máy Vlog Chân thực (Bỏ selfie 1 tay vươn dài)**: Tuyệt đối không mô tả cánh tay vươn dài gượng gạo xa tít làm hẹp góc nhìn và dễ lỗi dị tật tay. Thay vào đó, linh hoạt phối hợp 3 góc máy chuẩn Vlog: (a) *Lúc cần có Nora (Self-Vlog / Tự quay)*: Nora cầm máy tự nhiên ngang ngực/cổ quay mặt mình, nói trực tiếp vào ống kính dẫn dắt câu chuyện; (b) *Lúc Nora thao tác 2 tay & Cảnh rộng (In-Frame Host Experience)*: Máy quay đặt trên tảng đá/chạc cây hoặc góc máy trung/toàn (Tripod/Rock-mounted medium/wide shot), Nora xuất hiện rõ ràng trong khung hình (Full/Medium Nora in frame), thoải mái dùng cả hai tay trải nghiệm cơ chế sinh tồn (nếm súp tủy xương, ngồi sưởi ấm, đẽo đá, may đồ), vừa thao tác vừa quay mặt về phía camera vừa nói/giải thích kiểu người dẫn chương trình thực tế; (c) *Cận cảnh chi tiết (POV Close-Up)*: Camera quay cận cảnh đồ vật/hiện tượng (đá nung sủi bọt, mũi khâu gân) khi cần soi chi tiết. (4) **Chuẩn Thoại Dồn Dập Mới (23 – 25 từ / clip 8s)**: Nora nói nhanh, dồn dập, tự nhiên và tràn đầy năng lượng qua giọng Laomedeia (vừa vặn 7.0–7.5 giây của clip 8s), tạo cảm giác vlogger đang livestream thực tế với nhịp adrenaline cao. Không vượt quá 26 từ để tránh bị cụt âm thanh. (5) **Khóa Chuẩn Bối Cảnh Địa Lý/Thời Kỳ (Strictly No Snow)**: Tôn trọng đúng khí hậu thời kỳ (MIS 3 Neanderthal Dordogne là rừng thông ôn đới, đất mùn rêu xanh, tuyệt đối không tự ý chèn tuyết/bão mùa đông).
"""

_PIPELINE_OVERVIEW = """\
## Pipeline Order (Omni Flash R2V Ingredients Workflow)

```
0. Research          /fk-research "topic" (fact-check via web search, save to .omc/research/)
1. Health check      GET  /health → extension_connected: true
2. Create project    POST /api/projects (with entities + material, story from research)
3. Create video      POST /api/videos (HORIZONTAL or VERTICAL)
4. Create scenes     POST /api/scenes (with character_names, duration: 4/6/8/10s, video_prompt)
5. Gen ref images    POST /api/requests/batch (GENERATE_CHARACTER_IMAGE / upload locked refs)
                     Verify all key entities (Character, Body, Location) have UUID media_id
6. Gen videos (R2V)  POST /api/requests/batch (type: "GENERATE_VIDEO_REFS")
                     Omni Flash abra_r2v synthesizes clips directly from Ingredients (Face, Body dressed in outfit)
                     Auto-retry failed videos up to 5x; rolling download 720p clips to scenes/
6.5 Review videos   MANDATORY GATE! Trích xuất frames từ video 720p thô (CHƯA CẦN XÓA LOGO).
                     Display per-scene scorecard table + Review Board (http://localhost:8200).
                     STOP & PAUSE: User reviews each scene clip individually.
                     Nếu chưa đạt: sửa prompt -> REGENERATE_VIDEO (ở mức 720p, không tốn công xóa logo).
7. Upscale 1080p     CHỈ KHI USER DUYỆT CẢNH: POST /api/requests/batch (type: "UPSCALE_VIDEO", RPC p0UkFb)
                     Tải video 1080p về folder 1080/ -> ${OUTDIR}/1080/scene_XX_1080p.mp4
8. De-watermark      Chạy remove_watermark_video TRỰC TIẾP trên bản 1080p -> ${OUTDIR}/1080/scene_XX_1080p_clean.mp4
9. Concat           ffmpeg normalize + concat (dùng toàn bộ video 1080p clean đã duyệt)
10. SEO & Thumbnails Auto-match script language (e.g. 100% native Japanese for Japanese POV vlog)
```
"""

_BATCH_API = """\
## Batch API

Submit N requests at once (server paces them automatically — every Flow request spaced a random 45–60s, see rule 10):

```bash
curl -X POST http://127.0.0.1:8100/api/requests/batch \\
  -H "Content-Type: application/json" \\
  -d '{"requests": [{"type": "...", "scene_id": "...", "project_id": "...", "video_id": "...", "orientation": "VERTICAL"}, ...]}'
```

Poll aggregate status:

```bash
curl -s "http://127.0.0.1:8100/api/requests/batch-status?video_id=<VID>&type=GENERATE_IMAGE"
# Returns: {"total": 40, "pending": 30, "processing": 5, "completed": 5, "failed": 0, "done": false}
# When "done": true → all requests have left the queue (completed or failed)
# When "all_succeeded": true → every request completed successfully
```

For full API reference, workflow recipes, and video prompt guidelines, see `CLAUDE.md`.
"""


def _agents_md_body(skills, title):
    """Build the AGENTS.md body with the critical rules inlined."""
    rows = "\n".join(
        f"| `/fk-{s['name']}` | {s['description']} |" for s in skills
    )
    return (
        f"<!-- AUTO-GENERATED by setup.py — do not edit. Source: skills/ -->\n"
        f"# Flow Kit — {title}\n\n"
        f"Base URL: `http://127.0.0.1:8100`\n\n"
        f"## Pre-flight\n\n"
        f"Before ANY workflow:\n"
        f"```bash\n"
        f"curl -s http://127.0.0.1:8100/health\n"
        f"# Flow mode must return: {{\"extension_connected\": true}}\n"
        f"# Assistant mode (MEDIA_PROVIDER=assistant or provider=assistant per request):\n"
        f"# extension_connected may be false — no Chrome extension needed.\n"
        f"# Check provider status instead: GET /api/providers/status\n"
        f"```\n\n"
        f"{_CRITICAL_RULES}\n"
        f"{_PIPELINE_OVERVIEW}\n"
        f"{_BATCH_API}\n"
        f"## Skills\n\n"
        f"This project has reusable skills in `skills/`. When the user says `/fk-<name>`, "
        f"read `skills/fk-<name>.md` (or `skills/fk-<name>/SKILL.md` for a folder skill) "
        f"and follow the instructions inside.\n\n"
        f"| Skill | Purpose |\n"
        f"|-------|---------|\n"
        f"{rows}\n"
    )


def generate_codex(skills):
    """Generate AGENTS.md for Codex CLI."""
    content = _agents_md_body(skills, "Codex CLI Instructions")
    AGENTS_MD.write_text(content, encoding="utf-8")
    print(f"Generated AGENTS.md ({len(skills)} skills)")
    return len(skills)


def save_state(tools, skill_count):
    state = {
        "tools": tools,
        "last_sync": datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ"),
        "skill_count": skill_count,
    }
    STATE_FILE.write_text(json.dumps(state, indent=2), encoding="utf-8")


def load_state():
    if not STATE_FILE.exists():
        return None
    try:
        return json.loads(STATE_FILE.read_text(encoding="utf-8"))
    except (json.JSONDecodeError, OSError):
        return None


TOOLS = {
    "claude": generate_claude,
    "codex": generate_codex,
    "antigravity": generate_antigravity,
}


def run_generators(tools, skills):
    """Run the appropriate generators for the given tool list."""
    for tool in tools:
        if tool in TOOLS:
            TOOLS[tool](skills)
        else:
            # Reachable from a .fk-setup.json written before v1.3.1, which
            # records "gemini". Skipping beats crashing a sync on a target
            # that no longer exists; `clean` removes what it left behind.
            print(f"Skipping '{tool}' — no longer a supported target. "
                  f"Run 'python setup.py clean' to remove its leftover files.")


def do_interactive(skills):
    """Interactive mode: prompt user to pick tools."""
    print("\nFlow Kit — AI Tool Setup\n")
    print("Which AI tool do you drive this project from?")
    print("  [1] Claude Code       (.claude/commands/)")
    print("  [2] Codex CLI         (AGENTS.md)")
    print("  [3] Antigravity IDE   (.agents/skills/)")
    print("  [4] All tools")
    print()

    raw = input("Select (comma-separated, e.g. 1,2,3): ").strip()
    if not raw:
        print("No selection made. Exiting.")
        return

    mapping = {"1": "claude", "2": "codex", "3": "antigravity", "4": "all"}
    choices = [c.strip() for c in raw.split(",")]

    tools = []
    for c in choices:
        if c not in mapping:
            print(f"Invalid choice: {c}")
            continue
        val = mapping[c]
        if val == "all":
            tools = list(TOOLS)
            break
        if val not in tools:
            tools.append(val)

    if not tools:
        print("No valid tools selected. Exiting.")
        return

    run_generators(tools, skills)
    save_state(tools, len(skills))
    print(f"\nSetup complete. State saved to .fk-setup.json")


def do_tool(tool, skills):
    """Non-interactive: generate for a specific tool or all."""
    if tool == "all":
        tools = list(TOOLS)
    else:
        tools = [tool]
    run_generators(tools, skills)
    save_state(tools, len(skills))
    print(f"\nSetup complete. State saved to .fk-setup.json")


def do_sync(skills):
    """Re-sync all previously selected tools."""
    state = load_state()
    if not state:
        print("No previous setup found. Run 'python setup.py' first.")
        sys.exit(1)
    tools = state.get("tools", [])
    if not tools:
        print("No tools recorded in .fk-setup.json.")
        sys.exit(1)
    print(f"Re-syncing for tools: {', '.join(tools)}")
    run_generators(tools, skills)
    save_state(tools, len(skills))
    print(f"\nSync complete. {len(skills)} skills processed.")


def do_clean():
    """Remove all generated tool configs."""
    removed = []

    # Claude commands
    if CLAUDE_COMMANDS_DIR.exists():
        for f in CLAUDE_COMMANDS_DIR.glob("fk-*.md"):
            f.unlink()
            removed.append(str(f))

    # Antigravity skills
    if ANTIGRAVITY_SKILLS_DIR.exists():
        for d in ANTIGRAVITY_SKILLS_DIR.glob("fk-*"):
            if d.is_dir():
                shutil.rmtree(d)  # folder skills carry references/ subdirs
                removed.append(str(d))

    # Whatever the retired Gemini target left behind. Removed here even
    # though nothing writes it any more — an install from before v1.3.1 has
    # these files, and `clean` is the only thing that will ever take them away.
    if LEGACY_GEMINI_COMMANDS_DIR.exists():
        for f in LEGACY_GEMINI_COMMANDS_DIR.glob("*.toml"):
            f.unlink()
            removed.append(str(f))
        try:
            LEGACY_GEMINI_COMMANDS_DIR.rmdir()
            LEGACY_GEMINI_COMMANDS_DIR.parent.rmdir()   # .gemini/commands
            LEGACY_GEMINI_COMMANDS_DIR.parent.parent.rmdir()  # .gemini
        except OSError:
            pass  # not empty (agy keeps its own state here), leave it

    # AGENTS.md, plus the legacy GEMINI.md
    for md in [AGENTS_MD, LEGACY_GEMINI_MD]:
        if md.exists():
            first_line = md.read_text(encoding="utf-8", errors="replace").splitlines()[0]
            if "AUTO-GENERATED by setup.py" in first_line:
                md.unlink()
                removed.append(str(md))

    # State file
    if STATE_FILE.exists():
        STATE_FILE.unlink()
        removed.append(str(STATE_FILE))

    if removed:
        print(f"Removed {len(removed)} generated files.")
    else:
        print("Nothing to clean.")


def main():
    parser = argparse.ArgumentParser(
        description="Flow Kit — AI Tool Setup",
        add_help=True,
    )
    parser.add_argument(
        "subcommand",
        nargs="?",
        choices=["sync", "clean"],
        help="sync: re-sync previously selected tools | clean: remove all generated configs",
    )
    parser.add_argument(
        "--tool",
        choices=[*TOOLS, "all"],
        help="Generate configs for a specific tool (non-interactive)",
    )

    args = parser.parse_args()

    if args.subcommand == "clean":
        do_clean()
        return

    # All other subcommands need skill discovery
    skills = discover_skills()
    if not skills and args.subcommand != "clean":
        print("No skills found in skills/fk-*.md — nothing to generate.")
        sys.exit(1)

    if args.subcommand == "sync":
        do_sync(skills)
    elif args.tool:
        do_tool(args.tool, skills)
    else:
        do_interactive(skills)


if __name__ == "__main__":
    main()
